In [34]:
import pandas as pd
import numpy as np

In [35]:
df = pd.read_csv("StudentsPerformance.csv")
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

In [36]:
# Creating index
new_index = np.arange(0,1000)

In [37]:
np.random.shuffle(new_index)

In [38]:
df["new_index"] = new_index
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,new_index
0,female,group B,bachelor's degree,standard,none,72,72,74,747
1,female,group C,some college,standard,completed,69,90,88,924
2,female,group B,master's degree,standard,none,90,95,93,956
3,male,group A,associate's degree,free/reduced,none,47,57,44,600
4,male,group C,some college,standard,none,76,78,75,9

In [39]:
#set_index
df.set_index("new_index",inplace=True)
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
new_index,,,,,,,,
747,female,group B,bachelor's degree,standard,none,72,72,74
924,female,group C,some college,standard,completed,69,90,88
956,female,group B,master's degree,standard,none,90,95,93
600,male,group A,associate's degree,free/reduced,none,47,57,44
9,male,group C,some college,standard,none,76,78,75

In [45]:
# sorting by index
df.sort_index(ascending=True,inplace=True)
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
new_index,,,,,,,,
0,female,group C,some college,standard,none,71,81,80
1,male,group D,some college,standard,none,40,42,38
2,male,group C,high school,standard,none,88,89,86
3,male,group B,some college,standard,completed,88,85,76
4,female,group C,some high school,standard,none,47,54,53