In [1]:
import pandas as pd

In [4]:
df = pd.read_csv("StudentsPerformance.csv")
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

<h2>Sorting dataframe
</h2>

In [ ]:
# Inplace performs operation where dataframce is overwritten instead of copy
df.sort_values(["math score","reading score"],ascending=False,inplace=True)

In [14]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
149,male,group E,associate's degree,free/reduced,completed,100,100,93
458,female,group E,bachelor's degree,standard,none,100,100,100
916,male,group E,bachelor's degree,standard,completed,100,100,100
962,female,group E,associate's degree,standard,none,100,100,100
625,male,group D,some college,standard,completed,100,97,99

In [16]:
# sorting data, and making col values in lower
df.sort_values("race/ethnicity",ascending=True,key=lambda col:col.str.lower())

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
623,male,group A,some college,standard,completed,100,96,86
539,male,group A,associate's degree,standard,completed,97,92,86
546,female,group A,some high school,standard,completed,92,100,97
571,male,group A,bachelor's degree,standard,none,91,96,92
702,male,group A,bachelor's degree,standard,completed,87,84,87
...,...,...,...,...,...,...,...,...
807,female,group E,high school,free/reduced,none,41,45,40
383,female,group E,some high school,free/reduced,none,38,49,45
616,female,group E,bachelor's degree,standard,none,37,45,38
895,female,group E,some high school,free/reduced,none,32,34,38
76,male,group E,some high school,standard,none,30,26,22